import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Footer, NavBar } from "@/components";
import { FiCompass,FiHome,FiSettings,FiSearch} from "react-icons/fi";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen h-auto`}
      >
              <div className="w-full">
        <header className="bg-watercourse-400">
          <nav className="flex justify-between w-full bg-transparent text-white p-4">
            <a href="#">
              <span className="font-semibold text-xl tracking-tight">
                Title
              </span>
            </a>
            <div className="md:items-center md:w-auto flex">
              <div className="md:flex hidden">
                <Link className="block md:text-white mr-4 hover:underline" href="/explore/conocenos">
                  Conocenos
                </Link>
                <Link className="block md:text-white mr-4 hover:underline" href="/explore/ZOO">
                  Zoologicos
                </Link>
                <Link className="block md:text-white mr-4 hover:underline" href="/explore/ACUARIO">
                  Acuarios
                </Link>
                <Link className="block md:text-white mr-4 hover:underline" href="#">
                  Ayuda
                </Link>
              </div>
              <div className="flex text-sm" >
                <Link
                  className="p-2 ml-2 bg-white text-watercourse-500 font-semibold leading-none border border-gray-100 rounded hover:border-transparent hover:bg-gray-100"
                  href="/auth"
                >
                  Ingresar
                </Link>
                {/* <a
                  className="p-2 ml-2 bg-teal-500 text-gray-100 font-semibold leading-none border border-teal-600 rounded hover:border-transparent hover:bg-teal-600"
                  href="#"
                >
                  Sign up
                </a> */}
              </div>
            </div>
          </nav>
        </header>
        {/* <NavBar /> */}
        {children}
        <Footer/>
        <div className="bottomNav fixed bottom-0 w-full">
          {/* <nav
             style={{ border: "1px solid blue" }}
            className="md:hidden bottom-0 w-full bg-gray-700 text-xs"
           > */}
            {/* <ul className="flex justify-around items-center text-white text-center opacity-75 text-lg font-bold">
              <li className="p-4 hover:bg-gray-500">
                <a href="#">
                  <span>Link 1</span>
                  <svg
                    className="h-6 w-6 fill-current mx-auto"
                    viewBox="0 0 20 20"
                  >
                    <path
                      d="M14 8a4 4 0 1 0-8 0v7h8V8zM8.027 2.332A6.003 6.003 0 0 0 4 8v6l-3 2v1h18v-1l-3-2V8a6.003 6.003 0 0 0-4.027-5.668 2 2 0 1 0-3.945 0zM12 18a2 2 0 1 1-4 0h4z"
                      fill-rule="evenodd"
                    />
                  </svg>
                </a>
              </li>
              <li className="p-4 hover:bg-gray-500">
                <a href="#">
                  <span>Link 2</span>
                  <svg
                    className="h-6 w-6 fill-current mx-auto"
                    viewBox="0 0 20 20"
                  >
                    <path
                      d="M14 8a4 4 0 1 0-8 0v7h8V8zM8.027 2.332A6.003 6.003 0 0 0 4 8v6l-3 2v1h18v-1l-3-2V8a6.003 6.003 0 0 0-4.027-5.668 2 2 0 1 0-3.945 0zM12 18a2 2 0 1 1-4 0h4z"
                      fill-rule="evenodd"
                    />
                  </svg>
                </a>
              </li>
              <li className="p-4 hover:bg-gray-500">
                <a href="#">
                  <span>Link 3</span>
                  <svg
                    className="h-6 w-6 fill-current mx-auto"
                    viewBox="0 0 20 20"
                  >
                    <path
                      d="M14 8a4 4 0 1 0-8 0v7h8V8zM8.027 2.332A6.003 6.003 0 0 0 4 8v6l-3 2v1h18v-1l-3-2V8a6.003 6.003 0 0 0-4.027-5.668 2 2 0 1 0-3.945 0zM12 18a2 2 0 1 1-4 0h4z"
                      fill-rule="evenodd"
                    />
                  </svg>
                </a>
              </li>
              <li className="p-4 hover:bg-gray-500">
                <a href="#">
                  <span>Link 4</span>
                  <svg
                    className="h-6 w-6 fill-current mx-auto"
                    viewBox="0 0 20 20"
                  >
                    <path
                      d="M14 8a4 4 0 1 0-8 0v7h8V8zM8.027 2.332A6.003 6.003 0 0 0 4 8v6l-3 2v1h18v-1l-3-2V8a6.003 6.003 0 0 0-4.027-5.668 2 2 0 1 0-3.945 0zM12 18a2 2 0 1 1-4 0h4z"
                      fill-rule="evenodd"
                    />
                  </svg>
                </a>
              </li>
            </ul> */}
            <div className="px-7 bg-white shadow-lg rounded-2xl mb-5 md:hidden bottom-0 w-full ">
            <div className="flex">
                <div className="flex-auto hover:w-2/6 group">
                    <a href="#" className="flex items-center justify-center text-center mx-auto px-4 py-2 group-hover:w-full text-watercourse-500">
                        <span className="block px-1 py-1 border border-transparent group-hover:border-watercourse-500 rounded-full group-hover:flex-grow items-center">
                            {/* <i className="far fa-home text-2xl pt-1"></i> */}
                            <FiHome className="text-3xl group-hover:inline-block "/>
                            <span className="hidden group-hover:inline-block ml-3 align-bottom pb-1">Home</span>
                        </span>
                    </a>
                </div>
                <div className="flex-auto hover:w-2/6 group">
                    <a href="#" className="flex items-center justify-center text-center mx-auto px-4 py-2 group-hover:w-full text-watercourse-500">
                        <span className="block px-1 py-1 border border-transparent group-hover:border-watercourse-500 rounded-full group-hover:flex-grow">
                            {/* <i className="far fa-compass text-2xl pt-1"></i> */}
                            <FiCompass className="text-3xl group-hover:inline-block"/>
                            <span className="hidden group-hover:inline-block ml-3 align-bottom pb-1">Explore</span>
                        </span>
                    </a>
                </div>
                <div className="flex-auto hover:w-2/6 group">
                    <a href="#" className="flex items-center justify-center text-center mx-auto px-4 py-2 group-hover:w-full text-watercourse-500">
                        <span className="block px-1 py-1 border border-transparent group-hover:border-watercourse-500 rounded-full group-hover:flex-grow">
                            {/* <i className="far fa-search text-2xl pt-1"></i> */}
                            <FiSearch className="text-3xl group-hover:inline-block"/>
                            <span className="hidden group-hover:inline-block ml-3 align-bottom pb-1">Search</span>
                        </span>
                    </a>
                </div>
                <div className="flex-auto hover:w-2/6 group">
                    <a href="#" className="flex items-center justify-center text-center mx-auto px-4 py-2 group-hover:w-full text-watercourse-500">
                        <span className="block px-1 py-1 border border-transparent group-hover:border-watercourse-500 rounded-full group-hover:flex-grow">
                            {/* <i className="far fa-cog text-2xl pt-1"></i> */}
                            <FiSettings className="text-3xl group-hover:inline-block"/>
                            <span className="hidden group-hover:inline-block ml-3 align-bottom pb-1">Settings</span>
                        </span>
                    </a>
                </div>
            </div>
        </div>
          {/* </nav> */}
        </div>
      </div>
      </body>
    </html>
  );
}
